# Model arguments
model_name_or_path: deepseek-ai/deepseek-coder-7b-instruct-v1.5
# model_name_or_path: Srijith-rkr/deepseek_SFT_history # If you want to start from SFT checkpoint
# model_name_or_path: alignment-handbook/zephyr-7b-sft-full

# Data training arguments
use_local_dataset : true
use_cot : true # for the failed sampels 
use_only_failed_samples : true
local_dataset_mixer:
  - /home/srijithr/iterative-alignment/SPIN_implementation/ANLP_A4_ECCO/data/judge_base_deepseek_0_0.jsonl


dataset_splits:
- train
- test
preprocessing_num_workers: 12

dataset_mixer: # ignore this - only for testing purposes 
  #HuggingFaceH4/ultrafeedback_binarized: 1.0
  UCLA-AGI/SPIN_iter0: 1.0

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: false
hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-3
log_level: info
logging_steps: 2
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir:  /home/srijithr/iterative-alignment/SPIN_implementation/ANLP_A4_ECCO/temp_dir
# output_dir: /data/tir/projects/tir7/user_data/srijithr/anlp4_checkpoints # SRIJITH have to swich again.
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: null
seed: 42
warmup_ratio: 0.1

# Added to change default arguments
# output_dir: /data/tir/projects/tir7/user_data/srijithr/spin_outputs
run_name: lora_testing_anlp
use_peft : true
report_to: wandb
# lora_target_modules: 'k_proj q_proj v_proj'
# lora_target_modules: 'k_proj q_proj v_proj'
# lora_modules_to_save:
# - q_proj
# - k_proj
# - v_proj
lora_target_modules:
- q_proj
- k_proj
- v_proj
# Below are hard-coded
# bias: "none"
# task_type: "CAUSAL_LM"